services:
  payment-db:
    container_name: postgresql-payment
    image: postgres:latest
    environment:
      POSTGRES_DB: payment-db
      POSTGRES_USER: payment-postgres-user
      POSTGRES_PASSWORD: payment-postgres-pwd
    ports:
      - 5436:5432
    volumes:
      - /var/lib/postgres
    networks:
      - fiap05-postgres-network

networks:
  fiap05-postgres-network:
    driver: bridge
