spring:
  application:
    name: product
  jpa:
    show-sql: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/product-db
    username: product-postgres-user
    password: product-postgres-pwd
  flyway:
    baseline-on-migrate: true
    schemas: 'flyway'

server:
  port: 8082
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET:Fi@p-@lur@-2ADJT}
