spring:
  application:
    name: payment
  jpa:
    show-sql: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PAYMENT-POSTGRES-DB:jdbc:postgresql://localhost:5436/payment-db}
    username: ${PAYMENT-POSTGRES-USER:payment-postgres-user}
    password: ${PAYMENT-POSTGRES-PWD:payment-postgres-pwd}
  flyway:
    baseline-on-migrate: true
    schemas: 'flyway'

server:
  port: 8084
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET:Fi@p-@lur@-2ADJT}

base:
  url:
    http-user: ${URL_USER:http://localhost:8080}
    http-company: ${URL_COMPANY:http://localhost:8081}
    http-order: ${URL_ORDER:http://localhost:8083}
