spring:
  application:
    name: payment
  jpa:
    show-sql: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/payment-db
    username: payment-postgres-user
    password: payment-postgres-pwd
  flyway:
    baseline-on-migrate: true
    schemas: 'flyway'

server:
  port: 8084
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${API_SECURITY_TOKEN_SECRET:Fi@p-@lur@-2ADJT}

base:
  url:
    http-user: http://localhost:8080
    http-company: http://localhost:8081
    http-product: http://localhost:8082
    http-order: http://localhost:8083
