services:
  company-db:
    container_name: postgresql-company
    image: postgres:latest
    environment:
      POSTGRES_DB: company-db
      POSTGRES_USER: company-postgres-user
      POSTGRES_PASSWORD: company-postgres-pwd
    ports:
      - 5433:5432
    volumes:
      - /var/lib/postgres
    networks:
      - fiap05-postgres-network

networks:
  fiap05-postgres-network:
    driver: bridge